/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulo1;
import com.sun.xml.internal.ws.util.StringUtils;
import java.awt.Color;
import modulo1.reglas.nodo;
import javax.swing.*;
import java.util.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.ActionEvent;
import javax.swing.text.BadLocationException;
import javax.swing.GroupLayout.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;


import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Eduardo
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    JFrame f;
    nodo sintactico_terminado;
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_simbolos = new javax.swing.JTable();
        arbolView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultado_semantico = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Compilar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        tabla_simbolos.setForeground(new java.awt.Color(0, 0, 0));
        tabla_simbolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Identificador", "Ambito", "Valores | Parametros"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_simbolos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabla_simbolos);
        if (tabla_simbolos.getColumnModel().getColumnCount() > 0) {
            tabla_simbolos.getColumnModel().getColumn(0).setResizable(false);
            tabla_simbolos.getColumnModel().getColumn(1).setResizable(false);
            tabla_simbolos.getColumnModel().getColumn(2).setResizable(false);
            tabla_simbolos.getColumnModel().getColumn(3).setResizable(false);
        }

        arbolView.setText("Ver arbol");
        arbolView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolViewMouseClicked(evt);
            }
        });

        jLabel1.setText("Tabla de simbolos");

        editor.setColumns(20);
        editor.setRows(5);
        editor.setTabSize(1);
        jScrollPane3.setViewportView(editor);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Análisis Semantico");

        resultado_semantico.setEditable(false);
        jScrollPane4.setViewportView(resultado_semantico);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(arbolView, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(167, 167, 167))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(arbolView)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultTableModel model = (DefaultTableModel) this.tabla_simbolos.getModel();
        int tam = model.getRowCount();
        if (tam>0) {
            System.out.println("Tamaño tabla "+tam);
            while(tam>0){
                tam--;
                model.removeRow(tam);
            }
        }
        

        //System.out.println(editor.getText().toString().toString().replaceAll("\\s", " "));
        analizadorLexico lex = new analizadorLexico(editor.getText().toString().replaceAll("\\s"," "));
        
        ArrayList<token> tokens = lex.analizar();
        //int tam = tokens.size();
        /*for (int i = 0; i < tam; i++) {
            System.out.println(tokens.get(i).numero+"\t"+tokens.get(i).simbolo);
        }*/
        sintactico sintac = new sintactico(tokens);
        sintactico_terminado = sintac.analizar();
        ArrayList<String> listaSimbolos= new ArrayList<String>();
        ArrayList<String> semantico= new ArrayList<String>();
        sintactico_terminado.muestra(listaSimbolos, "Global", semantico);
        //sintactico_terminado.semantico(listaSimbolos, "Global", semantico);
        //System.out.println("Semantico"+semantico);
        //String resultado_analisis="";
        this.resultado_semantico.setText("");
        for (int i = 0; i <semantico.size(); i++) {
            javax.swing.text.StyledDocument doc = this.resultado_semantico.getStyledDocument();
            javax.swing.text.Style style = doc.addStyle("StyleName", null);
            
            String[] resp  = semantico.get(i).split("-");
            if (resp[0].equals("Success")) {
                javax.swing.text.StyleConstants.setForeground(style, Color.BLUE);
            }else if(resp[0].equals("Error")){
                javax.swing.text.StyleConstants.setForeground(style, Color.RED);
            }
            try{
                doc.insertString(doc.getLength(), semantico.get(i) + "\n", style);
            }
            catch (javax.swing.text.BadLocationException e) {
            }
        }
        for (int i = 0; i<listaSimbolos.size(); i++) {
            String temporal = listaSimbolos.get(i);
            //System.out.println(temporal);
            String[] partes =  temporal.split("-");
            if (partes.length>3) {
                model.addRow(new Object[]{partes[0],partes[1],partes[2],partes[3]});
            }else{
                model.addRow(new Object[]{partes[0],partes[1],partes[2]});          
            }
        }
        System.out.println(listaSimbolos);
    }//GEN-LAST:event_jButton1MouseClicked

    private void arbolViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolViewMouseClicked
        // TODO add your handling code here:
        if (sintactico_terminado!=null) {
            f=new JFrame();
             //construccion del arbol
            DefaultMutableTreeNode programa = sintactico_terminado.muestraGrafico();  
            System.out.println(programa);
            JTree arbol = new JTree(programa);

            JScrollPane scroll = new JScrollPane(arbol);
            f.getContentPane().add(scroll);
            f.pack();
            f.setVisible(true);
            f.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }else{
        
        }
        
    }//GEN-LAST:event_arbolViewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arbolView;
    private javax.swing.JTextArea editor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane resultado_semantico;
    private javax.swing.JTable tabla_simbolos;
    // End of variables declaration//GEN-END:variables
}
